import type { Metadata } from "next";import {
  ClerkProvider
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Tektur } from "next/font/google";
import "./globals.scss";
import { ThemeProvider } from "@/components/ThemeProvider"
import { Header } from "@/components/header";
import { SideBar } from "@/components/sidebar";
import { Toaster } from 'react-hot-toast';
import { currentUser } from "@clerk/nextjs/server";
import { LoginCard } from "@/components/loginCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tektur = Tektur ({
  variable: "--font-tektur",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await currentUser()
  return (
    <ClerkProvider>

      <html lang="pt-BR" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${tektur.variable} antialiased`}
        >


          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >

            <div>
              <Header/>

              <main className="">
                <div className="max-w-7xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

                    {user ? (

                      <div className="hidden lg:block lg:col-span-3">
                        <SideBar/>
                      </div>
                    ): (
                      <div className="lg:col-span-3">
                        <LoginCard/>
                      </div>
                    )}
                    <div className="lg:col-span-9">
                      {children}
                    </div>
                  </div>

                </div>
              </main>

            </div>
            
          </ThemeProvider>
          <Toaster/>

        </body>
      </html>

    </ClerkProvider>
  );
}
